#install.packages("RcppZiggurat")
#install.packages("fields")

library(dplyr)
library(sp)
library(devtools)
library(tidyr)
library(Matrix)
library(ggplot2)
library(gridExtra)
library(grid)
#library(mapproj)
library(RandomFields)
#library(verification)
library(foreach)
library(doParallel)
library(geoR)
#library(lubridate)
library(mgcv)
#library(varhandle)
#library(SDMTools)
#library(mixtools)
library(mvnfast)
library(parallelDist)
library(Rcpp)				#sourceCpp function
#library(ncdf4)
library(pracma)				#mod function
library(plyr)				#adply function
library(doParallel)
library(optimParallel)
#library(Rmpi)
#library(snow)
#library(psych)
library(Rfast)
library(fields)
library(MASS)
library(GpGp)
